package com.bnctDB.bnctDB.model

import java.time.LocalDateTime
import javax.persistence.*

@Entity
@Table(name = "bnct")
class BnctData(
    @Id
    @Column(name = "Полная дата")
    var Polnaia_data: LocalDateTime? = null,
    @Column(name = "H-/Конус (мА)")
    var H_Konus_mA: Double? = null,
    @Column(name = "H-/Линза Воблова/Слив (°C)")
    var H_Linza_Voblova_Sliv_C: Double? = null,
    @Column(name = "H-/Линза Воблова/Напор (°C)")
    var H_Linza_Voblova_Napor_C: Double? = null,
    @Column(name = "H-/Линза Воблова/Мощность (Вт)")
    var H_Linza_Voblova_Moshchnost_Vt: Double? = null,
    @Column(name = "H-/Линза Воблова/Поток (л/мин)")
    var H_Linza_Voblova_Potok_l_min: Double? = null,
    @Column(name = "H-/Напор IFM (л/мин)")
    var H_Napor_IFM_l_min: Double? = null,
    @Column(name = "H-/Слив IFM (л/мин)")
    var H_Sliv_IFM_l_min: Double? = null,
    @Column(name = "H-/Источник (Па)")
    var H_Istochnik_Pa: Double? = null,
    @Column(name = "H-/Дифф. откачка (Па)")
    var H_Diff_otkachka_Pa: Double? = null,
    @Column(name = "Bergoz/HEBL/Ток (мА)")
    var Bergoz_HEBL_Tok_mA: Double? = null,
    @Column(name = "Конус/1/Ток (мА)")
    var Konus_1_Tok_mA: Double? = null,
    @Column(name = "Конус/1/Центр (°C)")
    var Konus_1_Tsentr_C: Double? = null,
    @Column(name = "Конус/1/М Верх (°C)")
    var Konus_1_M_Verkh_C: Double? = null,
    @Column(name = "Конус/1/М Право (°C)")
    var Konus_1_M_Pravo_C: Double? = null,
    @Column(name = "Конус/1/М Низ (°C)")
    var Konus_1_M_Niz_C: Double? = null,
    @Column(name = "Конус/1/М Лево (°C)")
    var Konus_1_M_Levo_C: Double? = null,
    @Column(name = "Конус/1/Б Верх (°C)")
    var Konus_1_B_Verkh_C: Double? = null,
    @Column(name = "Конус/1/Б Право (°C)")
    var Konus_1_B_Pravo_C: Double? = null,
    @Column(name = "Конус/1/Б Низ (°C)")
    var Konus_1_B_Niz_C: Double? = null,
    @Column(name = "Конус/1/Б Лево (°C)")
    var Konus_1_B_Levo_C: Double? = null,
    @Column(name = "Конус/2/Ток (мА)")
    var Konus_2_Tok_mA: Double? = null,
    @Column(name = "Конус/2/Центр (°C)")
    var Konus_2_Tsentr_C: Double? = null,
    @Column(name = "Конус/2/М Верх (°C)")
    var Konus_2_M_Verkh_C: Double? = null,
    @Column(name = "Конус/2/М Право (°C)")
    var Konus_2_M_Pravo_C: Double? = null,
    @Column(name = "Конус/2/М Низ (°C)")
    var Konus_2_M_Niz_C: Double? = null,
    @Column(name = "Конус/2/М Лево (°C)")
    var Konus_2_M_Levo_C: Double? = null,
    @Column(name = "Конус/2/Б Верх (°C)")
    var Konus_2_B_Verkh_C: Double? = null,
    @Column(name = "Конус/2/Б Право (°C)")
    var Konus_2_B_Pravo_C: Double? = null,
    @Column(name = "Конус/2/Б Низ (°C)")
    var Konus_2_B_Niz_C: Double? = null,
    @Column(name = "Конус/2/Б Лево (°C)")
    var Konus_2_B_Levo_C: Double? = null,
    @Column(name = "ЭЛВ/Энергия (кэВ)")
    var ELV_Energiia_keV: Double? = null,
    @Column(name = "ЭЛВ/Beam0 (мА)")
    var ELV_Beam0_mA: Double? = null,
    @Column(name = "ЭЛВ/EnergyU get (кВ)")
    var ELV_EnergyU_get_kV: Double? = null,
    @Column(name = "ЭЛВ/EnergyU set (кВ)")
    var ELV_EnergyU_set_kV: Double? = null,
    @Column(name = "ЭЛВ/EnergyI (мА)")
    var ELV_EnergyI_mA: Double? = null,
    @Column(name = "ЭЛВ/Avarage (мА)")
    var ELV_Avarage_mA: Double? = null,
    @Column(name = "ЭЛВ/Sec1U (кВ)")
    var ELV_Sec1U_kV: Double? = null,
    @Column(name = "ЭЛВ/Sec1I (мА)")
    var ELV_Sec1I_mA: Double? = null,
    @Column(name = "ЭЛВ/IsolatorU (кВ)")
    var ELV_IsolatorU_kV: Double? = null,
    @Column(name = "ЭЛВ/IsolatorI (мА)")
    var ELV_IsolatorI_mA: Double? = null,
    @Column(name = "ЭЛВ/Dark (мА)")
    var ELV_Dark_mA: Double? = null,
    @Column(name = "Охл. диаф./1/Верх (°C)")
    var Okhl_diaf_1_Verkh_C: Double? = null,
    @Column(name = "Охл. диаф./1/Право (°C)")
    var Okhl_diaf_1_Pravo_C: Double? = null,
    @Column(name = "Охл. диаф./1/Низ (°C)")
    var Okhl_diaf_1_Niz_C: Double? = null,
    @Column(name = "Охл. диаф./1/Лево (°C)")
    var Okhl_diaf_1_Levo_C: Double? = null,
    @Column(name = "Охл. диаф./2/Верх (°C)")
    var Okhl_diaf_2_Verkh_C: Double? = null,
    @Column(name = "Охл. диаф./2/Право (°C)")
    var Okhl_diaf_2_Pravo_C: Double? = null,
    @Column(name = "Охл. диаф./2/Низ (°C)")
    var Okhl_diaf_2_Niz_C: Double? = null,
    @Column(name = "Охл. диаф./2/Лево (°C)")
    var Okhl_diaf_2_Levo_C: Double? = null,
    @Column(name = "Охл. диаф./3/Верх (°C)")
    var Okhl_diaf_3_Verkh_C: Double? = null,
    @Column(name = "Охл. диаф./3/Право (°C)")
    var Okhl_diaf_3_Pravo_C: Double? = null,
    @Column(name = "Охл. диаф./3/Низ (°C)")
    var Okhl_diaf_3_Niz_C: Double? = null,
    @Column(name = "Охл. диаф./3/Лево (°C)")
    var Okhl_diaf_3_Levo_C: Double? = null,
    @Column(name = "Охл. диаф./4/Верх (°C)")
    var Okhl_diaf_4_Verkh_C: Double? = null,
    @Column(name = "Охл. диаф./4/Право (°C)")
    var Okhl_diaf_4_Pravo_C: Double? = null,
    @Column(name = "Охл. диаф./4/Низ (°C)")
    var Okhl_diaf_4_Niz_C: Double? = null,
    @Column(name = "Охл. диаф./4/Лево (°C)")
    var Okhl_diaf_4_Levo_C: Double? = null,
    @Column(name = "Охл. диаф./5/Верх (°C)")
    var Okhl_diaf_5_Verkh_C: Double? = null,
    @Column(name = "Охл. диаф./5/Право (°C)")
    var Okhl_diaf_5_Pravo_C: Double? = null,
    @Column(name = "Охл. диаф./5/Низ (°C)")
    var Okhl_diaf_5_Niz_C: Double? = null,
    @Column(name = "Охл. диаф./5/Лево (°C)")
    var Okhl_diaf_5_Levo_C: Double? = null,
    @Column(name = "Li мишень/Ток (мА)")
    var Li_mishen_Tok_mA: Double? = null,
    @Column(name = "Li мишень/Центр (0) (°C)")
    var Li_mishen_Tsentr_0_C: Double? = null,
    @Column(name = "Li мишень/Низ-право (1) (°C)")
    var Li_mishen_Niz_pravo_1_C: Double? = null,
    @Column(name = "Li мишень/Право (2) (°C)")
    var Li_mishen_Pravo_2_C: Double? = null,
    @Column(name = "Li мишень/Верх-право (3) (°C)")
    var Li_mishen_Verkh_pravo_3_C: Double? = null,
    @Column(name = "Li мишень/Верх (4) (°C)")
    var Li_mishen_Verkh_4_C: Double? = null,
    @Column(name = "Li мишень/Верх-лево (5) (°C)")
    var Li_mishen_Verkh_levo_5_C: Double? = null,
    @Column(name = "Li мишень/Лево (6) (°C)")
    var Li_mishen_Levo_6_C: Double? = null,
    @Column(name = "Li мишень/Низ-лево (7) (°C)")
    var Li_mishen_Niz_levo_7_C: Double? = null,
    @Column(name = "Li мишень/Вода вход (л/мин)")
    var Li_mishen_Voda_vkhod_l_min: Double? = null,
    @Column(name = "Li мишень/Вода выход 1 (л/мин)")
    var Li_mishen_Voda_vykhod_1_l_min: Double? = null,
    @Column(name = "Li мишень/Вода выход 2 (л/мин)")
    var Li_mishen_Voda_vykhod_2_l_min: Double? = null,
    @Column(name = "Li мишень/Вакуум (Па)")
    var Li_mishen_Vakuum_Pa: Double? = null,
    @Column(name = "Li мишень 9/Центр (0) (°C)")
    var Li_mishen_9_Tsentr_0_C: Double? = null,
    @Column(name = "Li мишень 9/М Право (1) (°C)")
    var Li_mishen_9_M_Pravo_1_C: Double? = null,
    @Column(name = "Li мишень 9/Б Право (2) (°C)")
    var Li_mishen_9_B_Pravo_2_C: Double? = null,
    @Column(name = "Li мишень 9/М Верх (3) (°C)")
    var Li_mishen_9_M_Verkh_3_C: Double? = null,
    @Column(name = "Li мишень 9/Б Верх (4) (°C)")
    var Li_mishen_9_B_Verkh_4_C: Double? = null,
    @Column(name = "Li мишень 9/М Лево (5) (°C)")
    var Li_mishen_9_M_Levo_5_C: Double? = null,
    @Column(name = "Li мишень 9/Б Лево (6) (°C)")
    var Li_mishen_9_B_Levo_6_C: Double? = null,
    @Column(name = "Li мишень 9/М Низ (7) (°C)")
    var Li_mishen_9_M_Niz_7_C: Double? = null,
    @Column(name = "Li мишень 9/Б Низ (8) (°C)")
    var Li_mishen_9_B_Niz_8_C: Double? = null,
    @Column(name = "Боп-1М/Б2/Зал/Гамма (Зв/Ч)")
    var Bop_1M_B2_Zal_Gamma_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б2/Зал/Нейтроны (Зв/Ч)")
    var Bop_1M_B2_Zal_Neitrony_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б2/Кор/Гамма (Зв/Ч)")
    var Bop_1M_B2_Kor_Gamma_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б2/Кор/Нейтроны (Зв/Ч)")
    var Bop_1M_B2_Kor_Neitrony_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б3/Зал/Гамма (Зв/Ч)")
    var Bop_1M_B3_Zal_Gamma_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б3/Зал/Нейтроны (Зв/Ч)")
    var Bop_1M_B3_Zal_Neitrony_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б3/Кор/Гамма (Зв/Ч)")
    var Bop_1M_B3_Kor_Gamma_Zv_Ch: Double? = null,
    @Column(name = "Боп-1М/Б3/Кор/Нейтроны (Зв/Ч)")
    var Bop_1M_B3_Kor_Neitrony_Zv_Ch: Double? = null,
    @Column(name = "Li6/Нейтроны (шт/сек)")
    var Li6_Neitrony_sht_sek: Double? = null,
    @Column(name = "Li6/Гамма (шт/сек)")
    var Li6_Gamma_sht_sek: Double? = null,
    @Column(name = "Li6/Загрузка (%)")
    var Li6_Zagruzka_persent: Double? = null,
    @Column(name = "Li6/Интеграл нейтронов (шт)")
    var Li6_Integral_neitronov_sht: Double? = null,
    @Column(name = "Эфф. обдирки/Нейтралы I (мА)")
    var Eff_obdirki_Neitraly_I_mA: Double? = null,
    @Column(name = "Эфф. обдирки/Эфф. (%)")
    var Eff_obdirki_Eff_persent: Double? = null,
    @Column(name = "UltravoltPs/300V/U set (В)")
    var UltravoltPs_300V_U_set_V: Double? = null,
    @Column(name = "UltravoltPs/300V/I set (мА)")
    var UltravoltPs_300V_I_set_mA: Double? = null,
    @Column(name = "UltravoltPs/300V/U get (В)")
    var UltravoltPs_300V_U_get_V: Double? = null,
    @Column(name = "UltravoltPs/300V/I get (мА)")
    var UltravoltPs_300V_I_get_mA: Double? = null,
    @Column(name = "БДН/A/n (шт/сек)")
    var BDN_A_n_sht_sek: Double? = null,
    @Column(name = "БДН/A/g (шт/сек)")
    var BDN_A_g_sht_sek: Double? = null,
    @Column(name = "БДН/A/gn (шт/сек)")
    var BDN_A_gn_sht_sek: Double? = null,
    @Column(name = "БДН/A/gSv (Зв/Ч)")
    var BDN_A_gSv_Zv_Ch: Double? = null,
    @Column(name = "БДН/A/nSv (Зв/Ч)")
    var BDN_A_nSv_Zv_Ch: Double? = null,
    @Column(name = "БДН/B/n (шт/сек)")
    var BDN_B_n_sht_sek: Double? = null,
    @Column(name = "БДН/B/g (шт/сек)")
    var BDN_B_g_sht_sek: Double? = null,
    @Column(name = "БДН/B/gn (шт/сек)")
    var BDN_B_gn_sht_sek: Double? = null,
    @Column(name = "БДН/B/gSv (Зв/Ч)")
    var BDN_B_gSv_Zv_Ch: Double? = null,
    @Column(name = "БДН/B/nSv (Зв/Ч)")
    var BDN_B_nSv_Zv_Ch: Double? = null,
    @Column(name = "БДН/C/n (шт/сек)")
    var BDN_C_n_sht_sek: Double? = null,
    @Column(name = "БДН/C/g (шт/сек)")
    var BDN_C_g_sht_sek: Double? = null,
    @Column(name = "БДН/C/gn (шт/сек)")
    var BDN_C_gn_sht_sek: Double? = null,
    @Column(name = "БДН/C/gSv (Зв/Ч)")
    var BDN_C_gSv_Zv_Ch: Double? = null,
    @Column(name = "БДН/C/nSv (Зв/Ч)")
    var BDN_C_nSv_Zv_Ch: Double? = null,
    @Column(name = "Обдир миш/Слив (°C)")
    var Obdir_mish_Sliv_C: Double? = null,
    @Column(name = "Обдир миш/Напор (°C)")
    var Obdir_mish_Napor_C: Double? = null,
    @Column(name = "Обдир миш/Мощность (Вт)")
    var Obdir_mish_Moshchnost_Vt: Double? = null,
    @Column(name = "Обдир миш/Поток (л/мин)")
    var Obdir_mish_Potok_l_min: Double? = null,
    @Column(name = "Обдир миш/Аргон")
    var Obdir_mish_Argon: Double? = null,
    @Column(name = "HPGe/Мёртвое время (%)")
    var HPGe_Mertvoe_vremia_persent: Double? = null,
    @Column(name = "HPGe/Скорость в интеграле (шт/сек)")
    var HPGe_Skorost_v_integrale_sht_sek: Double? = null,
    @Column(name = "HPGe/Интеграл (шт)")
    var HPGe_Integral_sht: Double? = null,
    @Column(name = "ВФ (Bergoz/HEBL/Ток)/Флюенс (мАч)")
    var Vychisliator_fliuensa_Bergoz_HEBL_Tok_Fliuens_mAch: Double? = null,
    @Column(name = "ВФ (ЭЛВ/Beam0)/Флюенс (мАч)")
    var Vychisliator_fliuensa_ELV_Beam0_Fliuens_mAch: Double? = null,
    @Column(name = "ВФ (Боп-1М/Б2/Зал/Гамма)/Флюенс (мАч)")
    var Vychisliator_fliuensa_Bop_1M_B2_Zal_Gamma_Fliuens_mAch: Double? = null,
    @Column(name = "ВФ (Боп-1М/Б2/Зал/Нейтр)/Флюенс (мАч)")
    var Vychisliator_fliuensa_Bop_1M_B2_Zal_Neitrony_Fliuens_mAch: Double? = null,
    @Column(name = "ВФ (Li6/Нейтроны)/Флюенс (мАч)")
    var Vychisliator_fliuensa_Li6_Neitrony_Fliuens_mAch: Double? = null,
    @Column(name = "Ускоритель/ВОД/Слив (°C)")
    var Uskoritel_Vkhodnaia_okhlazhdaemaia_diafragma_Sliv_C: Double? = null,
    @Column(name = "Ускоритель/ВОД/Напор (°C)")
    var Uskoritel_Vkhodnaia_okhlazhdaemaia_diafragma_Napor_C: Double? = null,
    @Column(name = "Ускоритель/ВОД/Мощность (Вт)")
    var Uskoritel_Vkhodnaia_okhlazhdaemaia_diafragma_Moshchnost_Vt: Double? = null,
    @Column(name = "Ускоритель/ВОД/Поток (л/мин)")
    var Uskoritel_Vkhodnaia_okhlazhdaemaia_diafragma_Potok_l_min: Double? = null,
    @Column(name = "Вакуум/Ускоритель выход (Па)")
    var Vakuum_Uskoritel_vykhod_Pa: Double? = null,
    @Column(name = "Вакуум/HEBL После развертки (Па)")
    var Vakuum_HEBL_Posle_razvertki_Pa: Double? = null,
    @Column(name = "operatorPcDT")
    var operatorPcDT: LocalDateTime? = null,
    @Column(name = "journal")
    var journal: String? = null
    )